Presentation/FinPlus.Presentation/Controllers/TraferController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.Users;
    using FinPlus.Domain.Users.Trafer;
    using FinPlus.Presentation.Models;
    using FinPlusService;
    using FinPlusService.DefualtBet;
    using Microsoft.AspNetCore.Mvc;

    public class TraferController : Controller
    {
        private readonly ITraferService _trafferService;
        private readonly IDefaultBetService _defaultBetService;

        public TraferController(ITraferService trafferService, IDefaultBetService defaultBetService)
        {
            _trafferService = trafferService;
            _defaultBetService = defaultBetService;
        }

        public async Task<IActionResult> Index()
        {
            List<TraferModel> model = new List<TraferModel>();
            var traffers = await _trafferService.GetAllTraffers();

            foreach (var traffer in traffers)
            {
                TraferModel traferModel = new TraferModel()
                {
                    Id = traffer.Id,
                    Name = traffer.Name,
                    Login = traffer.Login,
                    Password = traffer.Password,
                    ReferalId = traffer.ReferalId,
                    MobileNumber = traffer.MobileNumber,
                    Level = traffer.Level,
                    Bet = traffer.Bet,
                    Revenue = await _trafferService.GetTrafferRevenue(traffer.Id),
                    ProfitInMonth = await _trafferService.GetTrafferProfitInMonth(traffer.Id, DateTime.Now.Month),
                };

                model.Add(traferModel);
            }

            return View(model);
        }

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> AddTrafer(TraferModel model, string name)
        {
            if (name == null)
            {
                return View(model);
            }

            var parts = name.Split(' ', StringSplitOptions.RemoveEmptyEntries);

            if (parts.Length < 2)
            {
                return BadRequest("Введите полное ФИО");
            }

            var fio = new FIO
            {
                Surname = parts[0],
                Name = parts[1],
                Patronymic = parts.Length > 2 ? parts[2] : string.Empty,
            };

            model.ReferalId = "001";
            string orgId = "000";
            TrafferBet bet = new TrafferBet()
            {
                Bet = await _defaultBetService.GetDefaultBetByOrganisationId(orgId),
            };

            Traffer trafer = new Traffer()
            {
                Name = fio,
                Login = model.Login,
                Password = model.Password,
                ReferalId = model.ReferalId,
                MobileNumber = model.MobileNumber,
                Level = model.Level,
                Bet = bet,
            };

            await _trafferService.AddTraffer(trafer);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditTrafer(string id)
        {
            var traffer = await _trafferService.GetTrafferById(id);
            return View(traffer);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateTraffer(Traffer traffer, string name)
        {
            if (ModelState.IsValid)
            {
                var parts = name.Split(' ', StringSplitOptions.RemoveEmptyEntries);

                if (parts.Length < 2)
                {
                    return BadRequest("Введите полное ФИО");
                }

                var fio = new FIO
                {
                    Surname = parts[0],
                    Name = parts[1],
                    Patronymic = parts.Length > 2 ? parts[2] : string.Empty,
                };
                traffer.Name = fio;
                await _trafferService.UpdateTraffer(traffer);
                return RedirectToAction("Index");
            }

            return View("EditTraffer", traffer);
        }
    }
}

Presentation/FinPlus.Presentation/Views/Trafer/AddTrafer.cshtml
@using FinPlus.Presentation.Models;
@model TraferModel

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Добавить Трафера</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4" style="border-bottom: 2px solid;">Добавить Трафера</h1>
        <form asp-controller="Trafer" asp-action="AddTrafer" method="post">
            <div class="mb-3">
                <label id="name" class="form-label">ФИО</label>
                <input id="name" name="name" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="Login" class="form-label">Логин</label>
                <input asp-for="Login" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="Password" class="form-label">Пароль</label>
                <input asp-for="Password" type="password" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="MobileNumber" class="form-label">Номер телефона</label>
                <input type="tel" class="form-control phone" id="mobileNumber" name="mobileNumber" placeholder="Номер телефона" asp-for="MobileNumber" required />
            </div>
            <div class="mb-3">
                <label asp-for="Level" class="form-label">Уровень</label>
                <select asp-for="Level" class="form-control" required>
                    <option value="1">Junior Referal</option>
                    <option value="2">Middle Referal</option>
                    <option value="3">Senior Referal</option>
                </select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Presentation/FinPlus.Presentation/Views/Trafer/EditTrafer.cshtml
@using FinPlus.Domain.Users.Trafer
@model Traffer

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Редактировать Трафера</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4" style="border-bottom: 2px solid;">Редактировать Трафера</h1>
        <form asp-action="UpdateTraffer" method="post">
            <div class="mb-3">
                <input asp-for="Id" class="form-control" required hidden />
            </div>
            <div class="mb-3">
                <label id="name" class="form-label">ФИО</label>
                <input id="name" name="name" class="form-control" value="@Model.Name.ToString()" required />
            </div>
            <div class="mb-3">
                <label asp-for="Login" class="form-label">Логин</label>
                <input asp-for="Login" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="Password" class="form-label">Пароль</label>
                <input asp-for="Password" class="form-control" required hidden />
            </div>
            <div class="mb-3">
                <label asp-for="ReferalId" class="form-label">Referal ID</label>
                <input asp-for="ReferalId" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="MobileNumber" class="form-label">Номер телефона</label>
                <input type="tel" class="form-control phone" id="mobileNumber" asp-for="MobileNumber" placeholder="Номер телефона" required />
            </div>
            <div class="mb-3">
                <label asp-for="Level" class="form-label">Уровень</label>
                <select asp-for="Level" class="form-control" required>
                    <option value="1">Junior Referal</option>
                    <option value="2">Middle Referal</option>
                    <option value="3">Senior Referal</option>
                </select>
            </div>
            <div class="mb-3">
                <label asp-for="Bet" class="form-label">Bet</label>
                <input asp-for="Bet" class="form-control" required />
            </div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Presentation/FinPlus.Presentation/Views/Trafer/Index.cshtml
@using FinPlus.Presentation.Models;
@model List<TraferModel>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Клиенты</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styletable.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/stylebtn.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <div class="header">Рефоводы</div>
        <div class="search-form">
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Найти</button>
            </form>
        </div>
        <div class="table-container">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>ФИО</th>
                        <th>Всего приведено</th>
                        <th>Всего заработано</th>
                        <th>Прибыль в текущем месяце</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var trafer in Model)
                    {
                        <tr>
                        <td>@trafer.ReferalId</td>
                        <td>@trafer.Name.ToString()</td>
                        <td>@trafer.MyDrops.Count()</td>
                        <td>@trafer.Revenue</td>
                        <td>@trafer.ProfitInMonth</td>
                        <td>
                            <a class="nav-link text-secondary" asp-controller="Trafer" asp-action="EditTrafer" asp-route-id="@trafer.Id">Ред.</a>
                        </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="nav-link text-secondary" asp-controller="Trafer" asp-action="AddTrafer">Добавить+</a>
        </div>
    </div>
</body>
</html>