Presentation/FinPlus.Presentation/Controllers/OrganisationController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.Organisations;
    using FinPlus.Domain.Users;
    using FinPlus.Domain.Users.Admin;
    using FinPlus.Presentation.Models;
    using FinPlusService;
    using FinPlusService.Organisation;
    using Microsoft.AspNetCore.Mvc;

    public class OrganisationController : Controller
    {
        private readonly IOrganisationService _organisationService;
        private readonly IAdminService _adminService;

        public OrganisationController(IOrganisationService organisationService, IAdminService adminService)
        {
            _organisationService = organisationService;
            _adminService = adminService;
        }

        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            var organisations = await _organisationService.GetAllOrganisations();
            List<OrganisationModel> model = new List<OrganisationModel>();
            foreach (var organisation in organisations)
            {
                OrganisationModel organisationModel = new OrganisationModel()
                {
                    Name = organisation.Name,
                    Id = organisation.Id,
                    MainAdmin = await _adminService.GetAdminById(organisation.MainAdminId),
                };
                model.Add(organisationModel);
            }

            return View(model);
        }

        public async Task<IActionResult> AddOrganisation(OrganisationModel model, string fio)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            if (string.IsNullOrEmpty(model.Name))
            {
                return View(model);
            }

            Organisation organisation = new Organisation()
            {
                Name = model.Name,
                Id = model.Id,
            };

            await _organisationService.AddOrganisation(organisation);
            organisation = await _organisationService.GetOrganisationByName(model.Name);

            var parts = fio.Split(' ', StringSplitOptions.RemoveEmptyEntries);

            if (parts.Length < 2)
            {
                return BadRequest("Введите полное ФИО");
            }

            var adminName = new FIO
            {
                Surname = parts[0],
                Name = parts[1],
                Patronymic = parts.Length > 2 ? parts[2] : string.Empty,
            };

            model.MainAdmin.OrganisationId = organisation.Id;
            model.MainAdmin.Name = adminName;

            await _adminService.AddAdmin(model.MainAdmin);
            var admin = await _adminService.GetAdminByOrganisationId(organisation.Id);

            organisation.MainAdminId = admin.Id;
            await _organisationService.UpdateOrganisation(organisation);
            return RedirectToAction("Index");
        }
    }
}

Presentation/FinPlus.Presentation/Views/Organisation/AddOrganisation.cshtml
@model FinPlus.Presentation.Models.OrganisationModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить организацию</title>
</head>
<body>
    <div class="container">
        <h2>Добавить организацию</h2>
        <form asp-action="AddOrganisation" method="post">
            <div class="form-group">
                <input asp-for="Id" class="form-control" hidden />
            </div>
            <div class="form-group">
                <label asp-for="Name">Название</label>
                <input asp-for="Name" class="form-control" />
            </div>
            <h2>Добавить администратора организации</h2>
            <div class="mb-3">
                <label id="fio" class="form-label">ФИО</label>
                <input id="fio" name="fio" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="MainAdmin.Login" class="form-label">Логин</label>
                <input asp-for="MainAdmin.Login" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="MainAdmin.Password" class="form-label">Пароль</label>
                <input asp-for="MainAdmin.Password" type="password" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="MainAdmin.MobileNumber" class="form-label">Номер телефона</label>
                <input asp-for="MainAdmin.MobileNumber" type="tel" class="form-control phone" placeholder="Номер телефона" required />
            </div>
            <div class="mb-3">
                <label asp-for="MainAdmin.Role" class="form-label">Уровень</label>
                <select asp-for="MainAdmin.Role" class="form-control" disabled>
                    <option value="1" selected>Admin</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Presentation/FinPlus.Presentation/Views/Organisation/Index.cshtml
@using FinPlus.Presentation.Models;
@model List<OrganisationModel>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Организации</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styletable.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/stylebtn.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <div class="header">Организации</div>
        <div class="table-container">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Название</th>
                        <th>Главный администратор</th>
                        <th>Номер ГА</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var organisation in Model)
                    {
                        <tr>
                            <td>@organisation.Name.</td>
                            <td>@organisation.MainAdmin.Name.ToString()</td>
                            <td>@organisation.MainAdmin.MobileNumber</td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="nav-link text-secondary" asp-controller="Organisation" asp-action="AddOrganisation">Добавить+</a>
        </div>
    </div>
</body>
</html>