Presentation/FinPlus.Presentation/Controllers/CalendarController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.CalendarOfDrops;
    using FinPlus.Presentation.Models;
    using FinPlusService.Calendar;
    using Microsoft.AspNetCore.Mvc;

    public class CalendarController : Controller
    {
        private readonly ICalendarService _calendarService;

        public CalendarController(ICalendarService calendarService)
        {
            _calendarService = calendarService;
        }

        public IActionResult Index()
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddDropRecord([FromBody] DropRecordModel model)
        {
            DateTime selectedDateTime = DateTime.Parse(model.SelectedHour);
            model.Record.Time = selectedDateTime;
            Records newRecord = new Records()
            {
                Day = selectedDateTime,
                DropRecords = model.Record,
                OrganisationId = "000",
            };
            await _calendarService.AddRecord(newRecord);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetDropRecordByDate(DateTime date)
        {
            var records = await _calendarService.GetDropRecordByDate(date);
            return Json(records);
        }
    }
}

Presentation/FinPlus.Presentation/Controllers/ClientController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.Offers;
    using FinPlus.Domain.Users;
    using FinPlus.Domain.Users.Drop;
    using FinPlus.Presentation.Models;
    using FinPlusService;
    using FinPlusService.Sources;
    using Microsoft.AspNetCore.Mvc;
    using WebApplication1.Models;

    public class ClientController : Controller
    {
        private readonly ILogger<ClientController> _logger;

        private readonly IDropService _dropService;

        private readonly ITraferService _traferService;

        private readonly ISourceService _sourceService;

        private readonly IOfferService _offerService;

        public ClientController(ILogger<ClientController> logger, IDropService dropService, IOfferService offerService, ITraferService traferService, ISourceService sourceService)
        {
            _logger = logger;
            _dropService = dropService;
            _offerService = offerService;
            _sourceService = sourceService;
            _traferService = traferService;
        }

        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            try
            {
                var drops = await _dropService.GetAllDrops();
                List<DropModel> model = new List<DropModel>();
                foreach (var drop in drops)
                {
                    DropModel dropModel = new DropModel()
                    {
                        Id = drop.Id,
                        Name = drop.Name.ToString(),
                        Partner = await _dropService.GetPartner(drop.ReferalId),
                        SubPartner = await _dropService.GetSubPartner(drop.ReferalId),
                        Source = await _dropService.GetPartner(drop.ReferalId),
                        MobileNumber = drop.MobileNumber,
                        Telegram = drop.Telegram,
                        Pass = drop.Pass.ToString(),
                        CardNumber = drop.CardNumber,
                        DateOfBirth = DateTime.SpecifyKind(drop.DateOfBirth, DateTimeKind.Utc).ToLocalTime(),
                        Date = DateTime.Parse(drop.Steps.Keys.First()),
                        ProfitPotencial = drop.ProfitPotencial,
                        RevenuePotential = drop.RevenuePotential,
                    };
                    model.Add(dropModel);
                }

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message, "Ошибка при получение списка клиентов с Базы");
                ErrorViewModel error = new ErrorViewModel(404);
                return RedirectToAction("Error", "Home", error);
            }
        }

        [HttpPost]
        [HttpGet]
        public async Task<IActionResult> AddClient(DropModel model, string comment)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            if (model.Name != null)
            {
                var parts = model.Name.Split(' ', StringSplitOptions.RemoveEmptyEntries);

                if (parts.Length < 2)
                {
                    return BadRequest("Введите полное ФИО");
                }

                var fio = new FIO
                {
                    Surname = parts[0],
                    Name = parts[1],
                    Patronymic = parts.Length > 2 ? parts[2] : string.Empty,
                };

                parts = model.Pass.Split(' ', StringSplitOptions.RemoveEmptyEntries);

                var pass = new DropPassport
                {
                    Series = parts[0],
                    Number = parts[1],
                };

                var orgId = HttpContext.Session.GetString("OrganisationId");

                Dictionary<string, List<Offer>> offers = new Dictionary<string, List<Offer>>()
                {
                    {
                        DropStep.FirstStep.ToString(), await _offerService.GetAllOffersById(model.Offers)
                    },
                };

                foreach (var offerList in offers.Values)
                {
                    foreach (var offer in offerList)
                    {
                        offer.Status = new Dictionary<string, OfferStatus>()
                        {
                            { DateTime.Now.ToString(), OfferStatus.InProgress },
                        };
                    }
                }

                Drop drop = new Drop()
                {
                    Name = fio,
                    Pass = pass,
                    MoneyStatus = false,
                    MobileNumber = model.MobileNumber,
                    Telegram = model.Telegram,
                    DateOfBirth = DateTime.SpecifyKind(model.DateOfBirth, DateTimeKind.Utc).ToLocalTime(),
                    OrganisationId = orgId,
                    Offers = offers,
                    Comments = model.Comment,
                    Steps = new Dictionary<string, DropStep> { { DateTime.Now.ToString(), DropStep.FirstStep } },
                    CardNumber = model.CardNumber,
                    ReferalId = model.Partner,
                };

                await _dropService.AddDrop(drop);
                return Json(new { success = true });
            }

            model.AllTraffers = await _traferService.GetAllTraffers();
            model.AllOffers = await _offerService.GetAllOffers();
            model.AllSources = await _sourceService.GetAllSources();
            return View(model);
        }

        public async Task<IActionResult> EditClient(DropModel model)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;
            var drop = await _dropService.GetDropById(model.Id);

            DropModel dropModel = new DropModel()
            {
                Name = drop.Name.ToString(),
                Partner = await _dropService.GetPartner(drop.ReferalId),
                SubPartner = await _dropService.GetSubPartner(drop.ReferalId),
                Source = await _dropService.GetPartner(drop.ReferalId),
                MobileNumber = drop.MobileNumber,
                Telegram = drop.Telegram,
                Pass = drop.Pass.ToString(),
                CardNumber = drop.CardNumber,
                DateOfBirth = DateTime.SpecifyKind(drop.DateOfBirth, DateTimeKind.Utc).ToLocalTime(),
                Date = DateTime.Parse(drop.Steps.Keys.First()),
                ProfitPotencial = drop.ProfitPotencial,
                RevenuePotential = drop.RevenuePotential,
                ReceivedOffers = drop.Offers,
                Comment = drop.Comments,
            };
            dropModel.AllTraffers = await _traferService.GetAllTraffers();
            dropModel.AllOffers = await _offerService.GetAllOffers();
            dropModel.AllSources = await _sourceService.GetAllSources();

            return View(dropModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateClientData(DropModel model)
        {
            if (model.Name != null)
            {
                var parts = model.Name.Split(' ', StringSplitOptions.RemoveEmptyEntries);

                if (parts.Length < 2)
                {
                    return BadRequest("Введите полное ФИО");
                }

                var fio = new FIO
                {
                    Surname = parts[0],
                    Name = parts[1],
                    Patronymic = parts.Length > 2 ? parts[2] : string.Empty,
                };

                parts = model.Pass.Split(' ', StringSplitOptions.RemoveEmptyEntries);

                var pass = new DropPassport
                {
                    Series = parts[0],
                    Number = parts[1],
                };

                await _dropService.UpdateDropData(model.Id, fio, model.Partner, pass, model.MobileNumber, model.CardNumber, model.PersonalReferalId, model.DateOfBirth, model.Telegram);
            }

            return RedirectToAction("EditClient", model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateClientStep(DropModel model, int step)
        {
            var offers = await _offerService.GetAllOffersById(model.Offers);
            bool success = await _dropService.UpdateDropStep(model.Id, step, offers, model.Comment[0]);

            return Json(new { success });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateClientOffer(string id, string offerId, DateOnly dateOffer, TimeOnly timeOffer, OfferStatus status)
        {
            DateTime date = DateTime.SpecifyKind(dateOffer.ToDateTime(timeOffer), DateTimeKind.Utc).ToLocalTime();
            await _dropService.UpdateDropOffer(id, offerId, date, status);
            DropModel model = new DropModel()
            {
                Id = id,
            };
            return RedirectToAction("EditClient", model);
        }

        public async Task<IActionResult> SearchClient(string partName)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            List<DropModel> model = new List<DropModel>();
            var drops = await _dropService.GetAllDropsByPartName(partName);
            return View("Index", model);
        }
    }
}

Presentation/FinPlus.Presentation/Controllers/OfferController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.Offers;
    using FinPlus.Presentation.Models;
    using FinPlusService;
    using Microsoft.AspNetCore.Mvc;

    public class OfferController : Controller
    {
        private readonly IOfferService _offerService;

        public OfferController(IOfferService offerService)
        {
            _offerService = offerService;
        }

        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            List<OfferModel> listOffers = new List<OfferModel>();
            var offers = await _offerService.GetAllOffers();
            foreach (var offer in offers)
            {
                OfferModel model = new OfferModel()
                {
                    Name = offer.Name,
                    Type = offer.Type,
                    TargetAction = offer.TargetAction,
                    Profit = offer.Profit,
                };

                listOffers.Add(model);
            }

            return View(listOffers);
        }

        public async Task<IActionResult> AddOffer(Offer model)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            if (model.Name == null)
            {
                return View(model);
            }

            await _offerService.AddOffer(model);

            return RedirectToAction("Index");
        }
    }
}

Presentation/FinPlus.Presentation/Controllers/SourceController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.Sources;
    using FinPlus.Presentation.Models;
    using FinPlusService.Sources;
    using Microsoft.AspNetCore.Mvc;

    public class SourceController : Controller
    {
        private readonly ISourceService _sourceService;

        public SourceController(ISourceService sourceService)
        {
            _sourceService = sourceService;
        }

        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            List<SourceModel> model = new List<SourceModel>();
            var sources = await _sourceService.GetAllSources();
            foreach (var source in sources)
            {
                SourceModel sourceModel = new SourceModel()
                {
                    Id = source.Id,
                    Name = source.Name,
                    ProfitInMonth = await _sourceService.GetSoureProfitInMonth(source.Id, DateTime.MinValue, DateTime.MaxValue),
                    Revenue = await _sourceService.GetSoureRevenue(source.Id),
                    MyDrops = await _sourceService.GetAllMyDrops(source.ReferalId),
                };
                model.Add(sourceModel);
            }

            return View(model);
        }

        public async Task<IActionResult> AddSource(Source source)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            if (source.Name == null)
            {
                return View(source);
            }

            source.ReferalId = "100";
            source.OrganizationId = "000";

            await _sourceService.AddSource(source);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditSource(string id)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            var source = await _sourceService.GetSourceById(id);
            return View(source);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSource(Source source)
        {
            if (ModelState.IsValid)
            {
                await _sourceService.UpdateSource(source);
                return RedirectToAction("Index");
            }

            return View("EditSource", source);
        }

        public async Task<IActionResult> SearchSource(string partName)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            var sources = await _sourceService.GetAllSourceByPartName(partName);
            List<SourceModel> model = new List<SourceModel>();

            foreach (var source in sources)
            {
                SourceModel sourceModel = new SourceModel()
                {
                    Id = source.Id,
                    Name = source.Name,
                    ProfitInMonth = await _sourceService.GetSoureProfitInMonth(source.Id, DateTime.MinValue, DateTime.MaxValue),
                    Revenue = await _sourceService.GetSoureRevenue(source.Id),
                    MyDrops = await _sourceService.GetAllMyDrops(source.ReferalId),
                };
                model.Add(sourceModel);
            }

            return View("Index", model);
        }
    }
}

Presentation/FinPlus.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinPlus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/stylenavpanel.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/stylebtn.css" asp-append-version="true" />
</head>
<body>
    @if (ViewBag.UserRole != null)
    {
        <div id="sidebarMenu" class="sidebar">
            @if (ViewBag.UserRole == "Admin" || ViewBag.UserRole == "MainAdmin" )
            {
                <a class="nav-link" asp-area="" asp-controller="Client" asp-action="Index">Клиенты</a>
                <a class="nav-link" asp-area="" asp-controller="Traffer" asp-action="Index">Партнеры</a>
                <a class="nav-link" asp-area="" asp-controller="Source" asp-action="Index">Источники</a>
                <a class="nav-link" asp-area="" asp-controller="Finance" asp-action="Index">Финансы</a>
                <a class="nav-link" asp-area="" asp-controller="Offer" asp-action="Index">Офферы</a>
                <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="Index">Календарь</a>
                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">Администрация</a>
                @if (ViewBag.UserRole == "MainAdmin")
                {
                    <a class="nav-link" asp-area="" asp-controller="Organisation" asp-action="Index">Организации</a>
                }
            }
            else if (ViewBag.UserRole == "Manager")
            {
                <a class="nav-link" asp-area="" asp-controller="Client" asp-action="Index">Клиенты</a>
                <a class="nav-link" asp-area="" asp-controller="Offer" asp-action="Index">Офферы</a>
                <a class="nav-link" asp-area="" asp-controller="Sources" asp-action="Index">Источники</a>
                <a class="nav-link" asp-area="" asp-controller="Calendar" asp-action="Index">Календарь</a>
            }
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Exit">Выход</a>
        </div>

        <div id="main">
            <button class="openbtn" onclick="toggleNav()">&#9776;</button>
            <div class="overlay" id="overlay" onclick="toggleNav()"></div>
            <main class="content">
                @RenderBody()
            </main>
        </div>
    }
    else
    {
        <div id="main">
            <main class="content">
                @RenderBody()
            </main>
        </div>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sciptnavpanel.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/FinPlus.Presentation/Views/Shared/_PostBackPartial.cshtml
@model FinPlus.Presentation.Models.DropModel

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/postback.css" />
    <title>Postback</title>
</head>
<body>
    <div class="container mt-5">
        <div class="header">
            <h1 class="font-weight-bold">Постбэк</h1>
            <form asp-action="UpdateClientOffer" class="form-inline" id="addOfferForm" method="post">
                <input asp-for="Id" id="Id" class="form-control" hidden />

                <label for="offerId">Оффер:</label>
                <select id="offerId" name="offerId" class="form-control" required>
                    @foreach (var offer in Model.AllOffers)
                    {
                        <option value="@offer.Id">@offer.Type-@offer.Name</option>
                    }
                </select>

                <label for="dateOffer">Дата:</label>
                <input type="date" id="dateOffer" name="dateOffer" class="form-control" required>

                <label for="timeOffer">Время:</label>
                <input type="time" id="timeOffer" name="timeOffer" class="form-control" required>

                <label for="status">Статус:</label>
                <select id="status" name="status" class="form-control" required>
                    <option value="0">Ожидает</option>
                    <option value="1">Одобрено</option>
                    <option value="2">Отклонено</option>
                    <option value="3">Отказано</option>
                    <option value="4">Получено</option>
                    <option value="5">ЦД сделано</option>
                    <option value="6">Отказался</option>
                    <option value="7">На будущее</option>
                    <option value="8">Есть</option>
                    <option value="9">Невозможно</option>
                    <option value="10">Потерян</option>
                </select>

                <button type="submit" class="btn btn-primary">Добавить</button>
            </form>

        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Оффер</th>
                    <th>Дата</th>
                    <th>Время</th>
                    <th>Статус</th>
                </tr>
            </thead>
            <tbody id="offersTableBody">
                @foreach (var offerList in Model.ReceivedOffers.Values)
                {
                    @foreach(var offer in offerList)
                    {
                        @foreach (var status in offer.Status)
                        {
                            <tr>
                                <td>@offer.Type-@offer.Name</td>
                                <td class="date-cell" data-datetime="@status.Key"></td>
                                <td class="time-cell" data-datetime="@status.Key"></td>
                                <td>@status.Value.GetDisplayName()</td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Функция для форматирования строки даты и времени
            function formatDateTime(dateTimeStr) {
                const [datePart, timePart] = dateTimeStr.split(' ');
                return {
                    date: datePart,
                    time: timePart
                };
            }

            // Обрабатываем ячейки даты
            document.querySelectorAll('.date-cell').forEach(function (cell) {
                const dateTimeStr = cell.getAttribute('data-datetime');
                if (dateTimeStr) {
                    const { date } = formatDateTime(dateTimeStr);
                    cell.textContent = date; // Заполняем дату в ячейку
                }
            });

            // Обрабатываем ячейки времени
            document.querySelectorAll('.time-cell').forEach(function (cell) {
                const dateTimeStr = cell.getAttribute('data-datetime');
                if (dateTimeStr) {
                    const { time } = formatDateTime(dateTimeStr);
                    cell.textContent = time; // Заполняем время в ячейку
                }
            });
        });
    </script>
</body>
</html>