Presentation/FinPlus.Presentation/Controllers/SourceController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.Sources;
    using FinPlus.Presentation.Models;
    using FinPlusService.Sources;
    using Microsoft.AspNetCore.Mvc;

    public class SourceController : Controller
    {
        private readonly ISourceService _sourceService;

        public SourceController(ISourceService sourceService)
        {
            _sourceService = sourceService;
        }

        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            List<SourceModel> model = new List<SourceModel>();
            var sources = await _sourceService.GetAllSources();
            foreach (var source in sources)
            {
                SourceModel sourceModel = new SourceModel()
                {
                    Id = source.Id,
                    Name = source.Name,
                    ProfitInMonth = await _sourceService.GetSoureProfitInMonth(source.Id, DateTime.MinValue, DateTime.MaxValue),
                    Revenue = await _sourceService.GetSoureRevenue(source.Id),
                    MyDrops = await _sourceService.GetAllMyDrops(source.ReferalId),
                };
                model.Add(sourceModel);
            }

            return View(model);
        }

        public async Task<IActionResult> AddSource(Source source)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            if (source.Name == null)
            {
                return View(source);
            }

            source.ReferalId = "100";
            source.OrganizationId = "000";

            await _sourceService.AddSource(source);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditSource(string id)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            var source = await _sourceService.GetSourceById(id);
            return View(source);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSource(Source source)
        {
            if (ModelState.IsValid)
            {
                await _sourceService.UpdateSource(source);
                return RedirectToAction("Index");
            }

            return View("EditSource", source);
        }

        public async Task<IActionResult> SearchSource(string partName)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            var sources = await _sourceService.GetAllSourceByPartName(partName);
            List<SourceModel> model = new List<SourceModel>();

            foreach (var source in sources)
            {
                SourceModel sourceModel = new SourceModel()
                {
                    Id = source.Id,
                    Name = source.Name,
                    ProfitInMonth = await _sourceService.GetSoureProfitInMonth(source.Id, DateTime.MinValue, DateTime.MaxValue),
                    Revenue = await _sourceService.GetSoureRevenue(source.Id),
                    MyDrops = await _sourceService.GetAllMyDrops(source.ReferalId),
                };
                model.Add(sourceModel);
            }

            return View("Index", model);
        }
    }
}

Presentation/FinPlus.Presentation/Controllers/TrafferController.cs
namespace FinPlus.Presentation.Controllers
{
    using FinPlus.Domain.Users;
    using FinPlus.Domain.Users.Trafer;
    using FinPlus.Presentation.Models;
    using FinPlusService;
    using FinPlusService.DefualtBet;
    using Microsoft.AspNetCore.Mvc;

    public class TrafferController : Controller
    {
        private readonly ITraferService _trafferService;
        private readonly IDefaultBetService _defaultBetService;

        public TrafferController(ITraferService trafferService, IDefaultBetService defaultBetService)
        {
            _trafferService = trafferService;
            _defaultBetService = defaultBetService;
        }

        public async Task<IActionResult> Index()
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            List<TrafferModel> model = new List<TrafferModel>();
            var traffers = await _trafferService.GetAllTraffers();

            foreach (var traffer in traffers)
            {
                TrafferModel traferModel = new TrafferModel()
                {
                    Id = traffer.Id,
                    Name = traffer.Name,
                    Login = traffer.Login,
                    Password = traffer.Password,
                    ReferalId = traffer.ReferalId,
                    MobileNumber = traffer.MobileNumber,
                    Level = traffer.Level,
                    Bet = traffer.Bet,
                    Revenue = await _trafferService.GetTrafferRevenue(traffer.Id),
                    ProfitInMonth = await _trafferService.GetTrafferProfitInMonth(traffer.Id, DateTime.Now.Month),
                };

                model.Add(traferModel);
            }

            return View(model);
        }

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> AddTraffer(TrafferModel model, string name)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            if (name == null)
            {
                return View(model);
            }

            var parts = name.Split(' ', StringSplitOptions.RemoveEmptyEntries);

            if (parts.Length < 2)
            {
                return BadRequest("Введите полное ФИО");
            }

            var fio = new FIO
            {
                Surname = parts[0],
                Name = parts[1],
                Patronymic = parts.Length > 2 ? parts[2] : string.Empty,
            };

            model.ReferalId = "001";
            var orgId = HttpContext.Session.GetString("OrganisationId");
            TrafferBet bet = new TrafferBet()
            {
                Bet = await _defaultBetService.GetDefaultBetByOrganisationId(orgId),
            };

            Traffer trafer = new Traffer()
            {
                Name = fio,
                Login = model.Login,
                Password = model.Password,
                ReferalId = model.ReferalId,
                MobileNumber = model.MobileNumber,
                Level = model.Level,
                Bet = bet,
                OrganisationId = orgId,
            };

            await _trafferService.AddTraffer(trafer);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditTraffer(string id)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            var traffer = await _trafferService.GetTrafferById(id);
            return View(traffer);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateTraffer(Traffer traffer, string name)
        {
            if (ModelState.IsValid)
            {
                var parts = name.Split(' ', StringSplitOptions.RemoveEmptyEntries);

                if (parts.Length < 2)
                {
                    return BadRequest("Введите полное ФИО");
                }

                var fio = new FIO
                {
                    Surname = parts[0],
                    Name = parts[1],
                    Patronymic = parts.Length > 2 ? parts[2] : string.Empty,
                };
                traffer.Name = fio;
                await _trafferService.UpdateTraffer(traffer);
                return RedirectToAction("Index");
            }

            return View("EditTraffer", traffer);
        }

        public async Task<IActionResult> SearchTraffer(string partName)
        {
            var role = HttpContext.Session.GetString("Role");
            ViewBag.UserRole = role;

            var traffers = await _trafferService.GetTrafferByPartName(partName);
            List<TrafferModel> model = new List<TrafferModel>();

            foreach (var traffer in traffers)
            {
                TrafferModel trafferModel = new TrafferModel()
                {
                    Id = traffer.Id,
                    Name = traffer.Name,
                    Login = traffer.Login,
                    Password = traffer.Password,
                    ReferalId = traffer.ReferalId,
                    MobileNumber = traffer.MobileNumber,
                    Level = traffer.Level,
                    Bet = traffer.Bet,
                    Revenue = await _trafferService.GetTrafferRevenue(traffer.Id),
                    ProfitInMonth = await _trafferService.GetTrafferProfitInMonth(traffer.Id, DateTime.Now.Month),
                };

                model.Add(trafferModel);
            }

            return View("Index", model);
        }
    }
}

Presentation/FinPlus.Presentation/Views/Source/AddSource.cshtml
@using FinPlus.Domain.Sources;
@model Source

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Добавить Трафера</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4" style="border-bottom: 2px solid;">Добавить Трафера</h1>
        <form asp-controller="Source" asp-action="AddSource" method="post">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Название</label>
                <input asp-for="Name" class="form-control" required />
            </div>
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Presentation/FinPlus.Presentation/Views/Source/EditSource.cshtml
@using FinPlus.Domain.Sources
@model Source

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Редактировать Источник</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4" style="border-bottom: 2px solid;">Редактировать Источник</h1>
        <form asp-action="UpdateSource" method="post">
            <div class="mb-3">
                <input asp-for="Id" class="form-control" required hidden />
            </div>
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Название</label>
                <input asp-for="Name" class="form-control" required />
            </div>
            <div class="mb-3">
                <label asp-for="ReferalId" class="form-label">Referal ID</label>
                <input asp-for="ReferalId" class="form-control" required />
            </div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Presentation/FinPlus.Presentation/Views/Source/Index.cshtml
@using FinPlus.Presentation.Models;
@model List<SourceModel>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Источники</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styletable.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/stylebtn.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <div class="header">Источники</div>
        <div class="search-form">
            <form asp-controller="Traffer" asp-action="SearchTraffer" method="post" class="form-inline">
                <input id="partName" name="partName" class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Найти</button>
            </form>
        </div>
        <div class="table-container">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название</th>
                        <th>Всего приведено</th>
                        <th>Всего заработано</th>
                        <th>Прибыль в текущем месяце</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var source in Model)
                    {
                        <tr>
                            <td>@source.ReferalId</td>
                            <td>@source.Name</td>
                            <td>@source.MyDrops.Count()</td>
                            <td>@source.Revenue</td>
                            <td>@source.ProfitInMonth</td>
                            <td>
                                <a class="nav-link text-secondary" asp-controller="Source" asp-action="EditSource" asp-route-id="@source.Id">Ред.</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="nav-link text-secondary" asp-controller="Source" asp-action="AddSource">Добавить+</a>
        </div>
    </div>
</body>
</html>